# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [mouse3687, tide, John, laff]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username copier
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/audible
community_bridge: # Replace with a single Community Bridge project-name e.g., Tornado.io
liberapay: # Replace with a single Liberapay username pitbull 
issuehunt: # Replace with a single IssueHunt username F35
otechie: # Replace with a single Otechie username Next
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://littledebbie.com', 'https://libertymutual.com, https://Harley-Davidson.com, https://energizer.com']
